name: Deploy n8n Production with PostgreSQL

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: false
        default: 'production'
        type: choice
        options:
          - production
          - staging
  push:
    branches:
      - main
      - master
    paths:
      - 'docker-compose-postgres.yml'
      - 'deploy-n8n-postgres.sh'
      - '.github/workflows/deploy-production-postgres.yml'

jobs:
  deploy-production:
    name: Deploy n8n with PostgreSQL
    # Usa el runner que ya tienes instalado llamado 'n8n'
    runs-on: self-hosted
    environment: ${{ inputs.environment || 'production' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create deployment directory
        run: |
          # Crear directorio con permisos para usuario n8n
          sudo mkdir -p /opt/n8n
          sudo chown n8n:n8n /opt/n8n

      - name: Copy deployment files
        run: |
          # Copiar archivos y asignar al usuario n8n
          sudo cp docker-compose-postgres.yml /opt/n8n/
          sudo cp deploy-n8n-postgres.sh /opt/n8n/
          sudo chown n8n:n8n /opt/n8n/*
          sudo chmod +x /opt/n8n/deploy-n8n-postgres.sh

      - name: Setup environment variables
        run: |
          # Ejecutar como usuario n8n
          sudo -u n8n bash -c '
            cd /opt/n8n

            # Generate secure passwords if not exists
            if [ ! -f .env ]; then
              echo "POSTGRES_PASSWORD=$(openssl rand -hex 16)" > .env
              echo "N8N_BASIC_AUTH_PASSWORD=$(openssl rand -hex 12)" >> .env
              echo "N8N_ENCRYPTION_KEY=$(openssl rand -base64 48)" >> .env
              echo "N8N_HOST=$(hostname -f)" >> .env
              echo "TZ=America/Mexico_City" >> .env
              echo "🔐 Generated new credentials in .env file"
            else
              echo "✅ Using existing .env file"
            fi

            # Load and display non-sensitive config
            source .env
            echo "📍 Host configured: $N8N_HOST"
          '

      - name: Stop existing containers
        run: |
          # Ejecutar como usuario n8n
          sudo -u n8n bash -c '
            cd /opt/n8n

            # Detectar si es podman o docker
            if command -v podman-compose &> /dev/null; then
              COMPOSE="podman-compose"
            else
              COMPOSE="docker-compose"
            fi

            # Stop existing services if running
            if [ -f docker-compose-postgres.yml ]; then
              $COMPOSE -f docker-compose-postgres.yml down 2>/dev/null || true
            fi
          '

      - name: Deploy with Docker Compose
        run: |
          # Ejecutar script como usuario n8n
          sudo -u n8n bash -c 'cd /opt/n8n && ./deploy-n8n-postgres.sh'

      - name: Health check
        run: |
          # Ejecutar health check como usuario n8n
          sudo -u n8n bash -c '
            cd /opt/n8n

            # Detectar runtime
            if command -v podman &> /dev/null; then
              RUNTIME="podman"
            else
              RUNTIME="docker"
            fi

            # Wait for services to start
            echo "⏳ Waiting for services to start..."
            sleep 30

            # Check PostgreSQL
            echo "🔍 Checking PostgreSQL..."
            $RUNTIME exec n8n-postgres pg_isready -U n8n || exit 1

            # Check n8n
            echo "🔍 Checking n8n..."
            curl -f http://localhost:5678/healthz || exit 1

            # Show running containers
            echo "📦 Running containers:"
            $RUNTIME ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" | grep -E "n8n|postgres"
          '

      - name: Display access information
        run: |
          echo "==============================================="
          echo "✅ Deployment completed successfully!"
          echo "==============================================="
          echo "🌐 Access n8n at: http://$(hostname -f):5678"
          echo "📝 Credentials are stored in: /opt/n8n/.env"
          echo ""
          echo "📊 To view credentials (on the server):"
          echo "   cat /opt/n8n/.env | grep -E 'BASIC_AUTH|PASSWORD'"
          echo ""
          echo "📋 Useful commands:"
          echo "   podman-compose -f /opt/n8n/docker-compose-postgres.yml logs -f"
          echo "   podman-compose -f /opt/n8n/docker-compose-postgres.yml ps"
          echo "==============================================="